export enum AdminEventName {
  PRODUCT_CREATED = 'PRODUCT.CREATED',
  PRODUCT_UPDATED = 'PRODUCT.UPDATED',
  PRODUCT_DELETED = 'PRODUCT.DELETED',
  PRODUCT_STOCK_UPDATED = 'PRODUCT.STOCK_UPDATED',
  NOTIFICATION_SENT = 'NOTIFICATION.SENT',
  NOTIFICATION_FAILED = 'NOTIFICATION.FAILED',
}
