export enum PublicEventName {
  HEALTH_CHECK_PASSED = 'HEALTH_CHECK.PASSED',
  HEALTH_CHECK_FAILED = 'HEALTH_CHECK.FAILED',
  USER_LOGIN = 'USER.LOGIN',
  USER_LOGOUT = 'USER.LOGOUT',
  USER_REGISTER = 'USER.REGISTER',
}
