export enum UserEventName {
  USER_CREATED = 'USER.CREATED',
  USER_UPDATED = 'USER.UPDATED',
  USER_DELETED = 'USER.DELETED',
  USER_LOGIN_STATUS = 'USER.LOGIN_STATUS',
  USER_PASSWORD_RESET = 'USER.PASSWORD_RESET',
  ORDER_CREATED = 'ORDER.CREATED',
  ORDER_UPDATED = 'ORDER.UPDATED',
  ORDER_DELETED = 'ORDER.DELETED',
  ORDER_STATUS_CHANGED = 'ORDER.STATUS_CHANGED',
  ORDER_PAYMENT_COMPLETED = 'ORDER.PAYMENT_COMPLETED',
}
